name: Build develop branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.201'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover

    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:        
        files: coverage.opencover.xml      
        directory: ./RecipeIngredientParser.Test/