name: Build master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput='./' /p:CoverletOutputFormat=opencover

    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:        
        files: ./coverage.opencover.xml      
        verbose: true

    - name: Push package to Nuget
      run: dotnet nuget push RecipeIngredientParser.Core/bin/Release/RecipeIngredientParser.Core.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate